using Avalonia.Controls;
using Avalonia.Markup.Xaml;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RMF_Server
{
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            this.DataContext = new MainViewModel();
        }

        private void InitializeComponent()
        {
            // This method is generated by the XAML designer and is responsible for initializing the UI components defined in MainWindow.axaml
            // You don't need to implement it manually, just make sure that the XAML file is properly set up and linked to this code-behind file
            AvaloniaXamlLoader.Load(this);
        }
    }
}
